### ISSUE TITLE
Cannot generate files

### ISSUE THREAD

**Issue by nf-PostQuantum** [dbrainio/Soltsice#1]
Steps to replicate:
* Follow the soltsice example project steps
** Run `soltsice contracts types`

Expected outcome:
* `.ts` files generated by soltsice

Actual outcome:
```
bash: soltsice: command not found
```

**Comment by buybackoff** [comment]
I have cloned my example and it works for me from scratch. Updated package version there: https://github.com/buybackoff/SoltsiceExample. Also using it in two other projects in this org.

What is your OS and Node.js version? Do you have files named `soltsice/soltsice.cmd` in `node_modules/.bin` after you run `npm install`?

**Comment by nf-PostQuantum** [comment]
OS: macOS Sierra 10.12.6
Node: 7.10
npm: 4.2.0
----
There is a file called `soltsice` in my `.bin`, trying to execute from there however returns:
`env: node\r: No such file or directory`

`.bin: ls -a`: 
```
.                       ansi-html               errno                   html-minifier           js-yaml                 loose-envify            ng                      nopt                    rimraf                  soltsice                stylus                  tsickle                 uuid
..                      babylon                 esparse                 image-size              jsesc                   miller-rabin            ng-xi18n                not-in-install          sassgraph               sshpk-conv              svgo                    tslint                  webdriver-manager
_mocha                  browserslist            esvalidate              in-install              json5                   mime                    ngc                     not-in-publish          semver                  sshpk-sign              truffle                 tsserver                webpack
_ts-node                cssesc                  handlebars              in-publish              karma                   mkdirp                  node-gyp                protractor              sha.js                  sshpk-verify            ts-node                 uglifyjs                webpack-dev-server
acorn                   csso                    he                      jasmine                 lessc                   mocha                   node-sass               regjsparser             solcjs                  strip-indent            tsc                     user-home               which

```

**Comment by buybackoff** [comment]
I am using Node 8.4/8.5, 8+ was needed for some dependency. Could you
please upgrade node and try again? I am on Windows, could try Mac later
today.

**Comment by buybackoff** [comment]
@nf-PostQuantum we have it working out of the box on different machines including Mac. Last time I tried on a new machine I didn't have `copyfiles` installed globally, maybe you have the same issue. Closing it for now.
