### ISSUE TITLE
 bin scripts should always have Unix line endings

### ISSUE THREAD

**Issue by StanleyGoldman** [dbrainio/Soltsice#14]
It works fine for me on windows, but on my Jenkins build server it breaks with the following
`/usr/bin/env: 'node\r': No such file or directory`

I do believe this is the issue.
https://github.com/npm/npm/issues/12371

I'm loving soltsice. Thanks for putting it together.

**Comment by StanleyGoldman** [comment]
`tr -d '\r' < ./node_modules/.bin/soltsice > ./node_modules/.bin/soltsice`

My temporary dirty fix

**Comment by buybackoff** [comment]
Thanks for reporting this! We have added Travis with Ubuntu recently, I thought it was enough to find any x-plat issues.

**Comment by StanleyGoldman** [comment]
I looked for how to fix it myself, but I get the i did not see where the file is being generated from.

**Comment by buybackoff** [comment]
In your link to the npm issue they say that it is npm packs the files in such way, as far as I understand. I changed my local git settings to always commit Unix style, not sure if that will help. Maybe you could try updating your npm to the latest version? This repo work fine on Travis's Ubuntu as well as our [contracts repo](https://github.com/dbrainio/dbrain-contracts) that uses Soltsice as npm dependency.

**Comment by StanleyGoldman** [comment]
So I changed my Jenkins script to use `npm install` instead of `yarn install` and everything works.
Thanks for entertaining me.
