### ISSUE TITLE
missing web3.isConnected function on W3

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#18]
Is W3 wrapper a full substitute for web3? Is there a way to get direct access to web3 via W3 if a method isn't implemented on W3 yet?

**Comment by buybackoff** [comment]
W3 is not a wrapper over web3 but rather a collection of most used methods implemented independently from web3. The fact that we use web3 is an implementation detail. You could access the web3 instance as `w3.web3` (w3 is an instance of W3)

**Comment by bjornharvold** [comment]
Thank you for elaborating. Much appreciated. I got it to work. 👍
