### ISSUE TITLE
error TS2345: Argument of type '(string | number | boolean | BigNumber)[]' is not assignable to parameter of type 'ContractDataType[]

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#20]
I am getting a variety of these errors:
/MiniMeToken.ts(50,13): error TS2345: Argument of type '(string | number | boolean | BigNumber)[]' is not assignable to parameter of type 'ContractDataType[]'
Type 'string | number | boolean | BigNumber' is not assignable to type 'ContractDataType'.
    Type 'BigNumber' is not assignable to type 'ContractDataType'.
      Type 'BigNumber' is not assignable to type 'BigNumber[]'.
        Property 'includes' is missing in type 'BigNumber'.

MultiSigWallet.ts(50,13): error TS2345: Argument of type '(number | string[] | BigNumber)[]' is not assignable to parameter of type 'ContractDataType[]'.
Type 'number | string[] | BigNumber' is not assignable to type 'ContractDataType'.
    Type 'BigNumber' is not assignable to type 'ContractDataType'.
      Type 'BigNumber' is not assignable to type 'BigNumber[]'.

These are standard MiniMeToken and MultiSigWallet implementations. I can't figure out what's happening here. I have about 10 classes that fail like this.

FYI I can compile and tests my contracts without errors.

<img width="1664" alt="minime_screengrab" src="https://user-images.githubusercontent.com/641791/36147457-da775a82-10ea-11e8-97db-0fd59eac9a7b.png">

**Comment by bjornharvold** [comment]
I found out the issue. My project had latest version of bignumber.js dependency ^6.0.0. Is there a requirement to not have the latest version or use the same version as Ethereum?

**Comment by buybackoff** [comment]
Yes, web3 v0.20 works with bignumber.js v.4.0.
We will migrate to BN.js soon when integrate with web3.js 1.0.

```
"peerDependencies": {
        "bignumber.js": "^4.0.0"
    },
```
