### ISSUE TITLE
TxParams explanation

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#22]
The TxParams interface is an optional attribute to every method. All its member variables are required. Can you please explain when and the best way to use it? 

For example, I have a method to set the start and end date of a contract. The method params that were created with Soltsice is (startdate, enddate, txParams). I have to add the contract owner account in txParams but I also have to include gas, gasPrice and the value. 

Cheers,
Bjorn

**Comment by buybackoff** [comment]
These are basically all parameters any wallet ask you (e.g. MetaMask). You could set default values but them override them for every individual call. There are [helper methods](https://github.com/dbrainio/Soltsice/blob/master/src/W3.ts#L583-L615) that are easier to use than to create the object manually (however it is not so difficult as well).
If you do not provide `txParams` all methods will fallback to a default one (e.g. [here](https://github.com/dbrainio/Soltsice/blob/master/src/contracts/DummyToken.ts#L64)). If you do not set the default value then web3 will complain that there is no `from` address.
