### ISSUE TITLE
Updated to new version of Soltsice 0.10.11 - Getting warning

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#24]
I recompiled my contracts and generated the Typescript classes. I then moved them over to my SPA project and updated Soltsice version there as well. I dropped node_modules. Rebuilt and try to start my app.

I received this warning:

```
WARNING in ./node_modules/soltsice/dist/soltsice.js
152:23-40 Critical dependency: the request of a dependency is an expression
```

**Comment by buybackoff** [comment]
On that line in the file inside `node_modules/soltsice/dist` try to change `require` to `require.resolve`. You are likely using Webpack and that behavior [is "by design"](https://github.com/mishoo/UglifyJS2/issues/2115#issuecomment-309182328).

**Comment by buybackoff** [comment]
I have exported type generation module, before it was just a script. With the export, webpack tries to process the module, while before it has just ignored it.

**Comment by bjornharvold** [comment]
function processFile(fileName, filePath, targetPath, W3ImportPath) {
        console.log('Processing ', filePath);
Line: 152        ==> var contract = require.resolve(filePath);
        var importPath = W3ImportPath;

Same error:
WARNING in ./node_modules/soltsice/dist/soltsice.js
152:23-40 Critical dependency: the request of a dependency is an expression
