### ISSUE TITLE
Question: Best way to estimate gas

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#26]
I am wondering how to best estimate gas for when calling contract methods using Soltsice.

**Comment by buybackoff** [comment]
Evenry method in generated contracts was `contract.methodName.estimateGas()`, e.g. [here](https://github.com/dbrainio/Soltsice/blob/11c7a774bf27961a0ab076f0afa4511e52d0e20d/src/contracts/DummyContract.ts#L160)

**Comment by bjornharvold** [comment]
Thank you :-)
