### ISSUE TITLE
v0.11.1 comes with errors

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#27]
I had to downgrade this morning after using this new release. I am getting these sort of errors:

ERROR in node_modules/soltsice/dist/SoltsiceContract.d.ts(33,115): error TS2304: Cannot find name 'AsyncIterableIterator'.
node_modules/soltsice/dist/SoltsiceContract.d.ts(37,137): error TS2304: Cannot find name 'AsyncIterableIterator'.
node_modules/soltsice/dist/SoltsiceContract.d.ts(38,138): error TS2304: Cannot find name 'AsyncIterableIterator'.

and

src/app/core/token-contract.service.ts(23,69): error TS2551: Property 'At' does not exist on type 'typeof TravelkoinCrowdsale'. Did you mean 'at'?
src/app/core/token-contract.service.ts(45,65): error TS2551: Property 'At' does not exist on type 'typeof TravelkoinToken'. Did you mean 'at'?
src/app/core/web3.service.ts(78,81): error TS2339: Property 'eth' does not exist on type 'W3'.
src/app/core/web3.service.ts(79,22): error TS2554: Expected 0 arguments, but got 2.
src/app/core/web3.service.ts(99,71): error TS2339: Property 'eth' does not exist on type 'W3'.
src/app/core/web3.service.ts(100,13): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<string[]>'.
  Type '{}' is not assignable to type 'string[]'.

Were there breaking changes? I also don't see a release of release notes for this.

Cheers,
Bjorn

**Comment by buybackoff** [comment]
AsyncIterableIterator is an alternative to Rx, but is not universally supported yet and need tsconfig setting.

In v.0.11. I renamed all method to JS standard camelCase. https://github.com/dbrainio/Soltsice/commit/ab9774073034ed24a1d0cc05f64e1caea69777da

**Comment by bjornharvold** [comment]
How do I get this new version to run? What do I need to do? Cheers

**Comment by buybackoff** [comment]
Rename all methods starting with a capital letter to camelCase.

Add `"downlevelIteration": true` and "esnext" to "lib" section in
tsconfig.json (
https://github.com/dbrainio/Soltsice/blob/master/tsconfig.json#L10).
However, given lack of default iterators support I may revert changes. It's
all about events from #25.

**Comment by buybackoff** [comment]
> Were there breaking changes? I also don't see a release of release notes for this.
There is not release tag for 0.11, it's WIP. I need NPM to test issues like these ones.

> src/app/core/web3.service.ts(78,81): error TS2339: Property 'eth' does not exist on type 'W3'.
I have removed `eth` property because it depends on `w3.web3` version. You could always use untyped `w3.web3.eth` and cast it to `W3.Eth` if needed.

**Comment by bjornharvold** [comment]
Go with RXJS :-) Should I stay at 0.10.11 until this has been resolved?

**Comment by buybackoff** [comment]
Please try 0.11.3, I removed the iterators stuff and fixed one bug when number was overflowing in `toHex` when larger than `2^31`.

**Comment by bjornharvold** [comment]
Works great.
